### ISSUE TITLE
setting of timeout?

### ISSUE THREAD

**Issue by jingpengw** [JuliaCloud/AWSCore.jl#9]
the default timeout in Requests.jl is `inf`, which seems not reasonable. 

I was using AWSS3 and got `ECONNRESET` error occasionally. This `ECONNRESET` error was not caught and could not be handled. If it is timeout error, should be easy to catch and handle. 

```
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)                       │················
 in yieldto(::Task, ::ANY) at ./event.jl:136                                                        │················
 in wait() at ./event.jl:169                                                                        │················
 in wait(::Condition) at ./event.jl:27                                                              │················
 in wait_readnb(::TCPSocket, ::Int64) at ./stream.jl:303                                            │················
 in eof(::TCPSocket) at ./stream.jl:58                                                              │················
 in macro expansion at /root/.julia/v0.5/Requests/src/streaming.jl:66 [inlined]                     │················
 in (::Requests.##6#8{Requests.ResponseStream{TCPSocket},Requests.ResponseParser,Channel{Symbol}})()│················
 at ./event.jl:68
```

**Comment by kilminster** [comment]
I'm guessing this is the reason that Sam is moving to HTTP.jl, rather than Requests.jl?

This unhandled ECONNRESET error has been bothering us for a long time.  Right now, I'm using a patched Requests.jl similar to https://github.com/JuliaWeb/Requests.jl/pull/165

**Comment by samoconnor** [comment]
@kilminster I found that [exception handling](https://github.com/JuliaCloud/AWSCore.jl/commit/36b4625d5cd1e0f15e028e24629f2b788173a7ea#diff-c77366a0be20e3d5b3b306c15a131951L76) was [not straight forward](https://github.com/JuliaCloud/AWSCore.jl/commit/36b4625d5cd1e0f15e028e24629f2b788173a7ea#diff-c77366a0be20e3d5b3b306c15a131951L101) with Requests.jl and I had to [mess around with the internals](https://github.com/JuliaCloud/AWSCore.jl/commit/36b4625d5cd1e0f15e028e24629f2b788173a7ea#diff-c77366a0be20e3d5b3b306c15a131951L68) to get some things working.

So, when @quinnj [announced that he was making it all better with HTTP.jl](https://discourse.julialang.org/t/ann-new-http-jl-package/2048) I though it was worth a try.

However, there are a number of unresolved issues with HTTP.jl also:
-  https://github.com/JuliaWeb/HTTP.jl/issues/58#issuecomment-323573444
-  https://github.com/JuliaWeb/HTTP.jl/issues/73 
-  https://github.com/JuliaWeb/HTTP.jl/issues/69
-  https://github.com/JuliaWeb/HTTP.jl/issues/40#issuecomment-315281051

If this stuff is resolved soon I'll probably stick with HTTP.jl in AWSCore.jl.
Note that I haven't tagged AWSCore.jl since merging my HTTP.jl branch into master. If I have a need to push out a new version of AWSCore.jl before the HTTP.jl rough edges are cleaned up, I'll revert to Requests.jl for the time being...

**Comment by samoconnor** [comment]
AWSCore.jl master is now using HTTP.jl.
Is there still a problem here?

**Comment by jingpengw** [comment]
I have not got a chance to reproduce it. Anyway, I have better error handling and retry to deal with this problem.
